<?xml version="1.0" encoding="utf-8"?><Database Name="PilotDB" Class="EventLoggerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-TJP5ALT\SQLEXPRESS;Initial Catalog=PilotDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PilotDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.App" Member="Apps">
    <Type Name="App">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="App_Event" Member="Events" ThisKey="Id" OtherKey="App_Id" Type="Event" />
      <Association Name="App_Event_Aggregate" Member="Event_Aggregates" ThisKey="Id" OtherKey="App_Id" Type="Event_Aggregate" />
    </Type>
  </Table>
  <Table Name="dbo.EventType" Member="EventTypes">
    <Type Name="EventType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Reportable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EventType_Event" Member="Events" ThisKey="Id" OtherKey="EventType_Id" Type="Event" />
      <Association Name="EventType_Event_Aggregate" Member="Event_Aggregates" ThisKey="Id" OtherKey="EventType_Id" Type="Event_Aggregate" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="App_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="App_Event" Member="App" ThisKey="App_Id" OtherKey="Id" Type="App" IsForeignKey="true" />
      <Association Name="EventType_Event" Member="EventType" ThisKey="EventType_Id" OtherKey="Id" Type="EventType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_Aggregate" Member="Event_Aggregates">
    <Type Name="Event_Aggregate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventType_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="App_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="App_Event_Aggregate" Member="App" ThisKey="App_Id" OtherKey="Id" Type="App" IsForeignKey="true" />
      <Association Name="EventType_Event_Aggregate" Member="EventType" ThisKey="EventType_Id" OtherKey="Id" Type="EventType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>