//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Last30
    {
        public Nullable<int> App_Id { get; set; }
        public int EventType_Id { get; set; }
        public Nullable<int> count { get; set; }
    }
}
